### ISSUE TITLE
Kafka UI with Upstash Kafka

### ISSUE THREAD

**Issue by JonhnyDev** [upstash/issues#31]
This config:
```
kafka:
  clusters:
    - name: myclustername
      bootstrapServers: "url:9092"
      properties:
        sasl.mechanism: SCRAM-SHA-512
        security.protocol: SASL_SSL
        sasl.jaas.config: org.apache.kafka.common.security.scram.ScramLoginModule required username="user" password="pass";    
```
return kafka UI in blank (without topics, consumes...)

and this configuration with docker composer:
```
version: '2'
services:
  kafka-ui:
    image: provectuslabs/kafka-ui
    container_name: kafka-ui
    ports:
      - "8080:8080"
    restart: always
    environment:
      - KAFKA_CLUSTERS_0_NAME=myclustername
      - KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=url:9092
      - KAFKA_CLUSTERS_0_PROPERTIES_SECURITY_PROTOCOL=SASL_SSL
      - KAFKA_CLUSTERS_0_PROPERTIES_SASL_MECHANISM=SCRAM-SHA-512
      - KAFKA_CLUSTERS_0_PROPERTIES_SASL_JAAS_CONFIG=org.apache.kafka.common.security.scram.ScramLoginModule required username='user' password='pass'
```

return this error:
![image](https://user-images.githubusercontent.com/43152652/189400184-5fc0424b-3cc4-4bfb-8b7f-7f6fba11a419.png)

500 Internal Server Error
Error while creating AdminClient for Cluster myclustername

user, pass, url and port working with NodeJS to producer and consume.
